# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: python

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build and Test'
          script:
            - docker login -u eivantsov -p ${DOCKER_PASSWORD}
            - pip install docker
            - python release_maker.py
          services:
            - docker
